name = "pitlane-web"
main = "worker/index.js"
compatibility_date = "2024-11-01"
account_id = "dc344532c11330ddd28198123f1bf95f"
workers_dev = true

[[kv_namespaces]]
binding = "DB"
id = "c12934f2ad4f49f8a006356a831b80a6"

[assets]
directory = "./client/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
PUBLIC_URL = "https://pitlane-web.pitlane-taksimaga.workers.dev"
